### ISSUE TITLE
New service coming

### ISSUE THREAD

**Issue by wkearney99** [CJNE/pyporscheconnectapi#11]
I got this e-mail from Porsche today:

> Dear Customer,
> 
> On behalf of Porsche, we are delighted to inform you that a new app is currently being developed that will soon be available in the App Store and in the Google Play Store. 
> 
> The new app will combine the services of several already existing Porsche apps, including the Porsche Car Connect app. 
> 
> This ensures a ‘one of a kind’ user experience and a maximum of connectivity between you and your vehicle. 
> 
> We will soon give you more information about it but, please, note that the current Porsche Car Connect app will shortly be removed from the stores, therefore shortly unavailable for using.
> 
> If you have any specific questions regarding the new app, please email your local Porsche Customer Service at customersupport@porsche.com.
> 
> We are looking forward to contacting you with further details.
> 
> Kind regards,
> Vodafone Automotive
> 

![porsch launch app](https://user-images.githubusercontent.com/232313/146403297-643c22c1-8f39-4351-a605-736b92eedc81.png)

**Comment by CJNE** [comment]
Hi!
Did this change anything for your ability to use the library?
