### ISSUE TITLE
API not working anymore - problem of Porsche servers?

### ISSUE THREAD

**Issue by TimoD87** [CJNE/pyporscheconnectapi#21]
Since today, the API is not working anymore, getting error:

`python cli.py -e mail@mail.me -p 665544 overview -v 'WP00124599564'`

`Traceback (most recent call last): File "/home/pi/pypo-main/cli.py", line 4, in <module> cli() File "/home/pi/pypo-main/pyporscheconnectapi/cli.py", line 273, in cli loop.run_until_complete(main(args)) File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "/home/pi/pypo-main/pyporscheconnectapi/cli.py", line 70, in main data = await client.getCurrentOverview(vin) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/pi/pypo-main/pyporscheconnectapi/client.py", line 462, in getCurrentOverview f"https://api.porsche.com/service-vehicle/{self.locale_str}/vehicle-data/{vin}/current/request/{progressResult['requestId']}/status" ~~~~~~~~~~~~~~^^^^^^^^^^^^^ KeyError: 'requestId' ERROR:asyncio:Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x7f938eca90> ERROR:asyncio:Unclosed connector connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f92701630>, 287032.570127384)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7f92550a60>, 287032.646862502)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7f92552190>, 287036.45946109)]'] connector: <aiohttp.connector.TCPConnector object at 0x7f928d0d10>`

Same problems out there ?

**Comment by CJNE** [comment]
Should be fixed in 0.0.26, re-open if you still have issues with this, thanks :)
