### ISSUE TITLE
Token refresh?

### ISSUE THREAD

**Issue by andig** [CJNE/pyporscheconnectapi#28]
Seems the new identity manager supports token refresh (`scopes_supported: offline_access`). A simple exchange doesn't do the trick though- probably needs additional headers. Any idea how token refresh could be supported?

**Comment by CJNE** [comment]
Oh that's interesting, I'll investigate. It depends on wether they have auth0 configured correctly though:
https://community.auth0.com/t/accesstokenerror-when-requesting-offline-access-scope/62813

**Comment by andig** [comment]
I've managed to request `offline_access` and get the refresh token, but failed on the refresh.

**Comment by fredriklj** [comment]
I am closing this issue as the APIs we relied on have been retired. C.f #46
