### ISSUE TITLE
Error: Invalid captcha value

### ISSUE THREAD

**Issue by Dual01** [CJNE/pyporscheconnectapi#32]
when I try to retrieve the car data, I get the error message 'invalid captcha value'.
Something seems to have been changed on the server

**Comment by Dual01** [comment]
works again, seemed to be a network problem

**Comment by martijndierckx** [comment]
I think Auth0 is showing a captcha on some occasions:
<img width="523" alt="image" src="https://github.com/CJNE/pyporscheconnectapi/assets/3973630/dcd18145-9f31-4027-a52a-a7cd876d6ad9">

But I'm not sure, when it does ...

**Comment by martijndierckx** [comment]
Seems my IP has been (hopefully temporarily) blacklisted.
Because when I try it over LTE on my phone, it doesn't show the captcha.

More info: https://auth0.com/docs/secure/attack-protection/bot-detection

**Comment by martijndierckx** [comment]
Looks like it takes about 72hours for Auth0 to reset an IP address.
I'm no longer seeing any Captcha...
