### ISSUE TITLE
Sending navigation to PCM

### ISSUE THREAD

**Issue by wdanilo** [CJNE/pyporscheconnectapi#33]
Hi, would it be possible to send navigation route to PCM? MyPorsche app has the ability to plan route and send it to vehicle. I want to create route via Google Maps and then send it to PCM :)

**Comment by fredriklj** [comment]
That would have been a nice feature, but I don't think any of the current contributors to the project have the time to implement it. Should you work out a solution, don't hesitate to file a PR.

**Comment by wdanilo** [comment]
In such a case, why are you closing this issue? I think it should stayed opened, as it is a valid request, right? :)
