### ISSUE TITLE
Anyone else seeing issues in past 24 hours+

### ISSUE THREAD

**Issue by augmentedtraffic** [CJNE/pyporscheconnectapi#34]
Can anyone else confirm they are seeing issues? I am wondering if it is just me (I can login to the porsche mobile app, but the API doesn't appear to work).

thanks in advance

Traceback (most recent call last):
  File "/home/pi/./porsche1.py", line 140, in <module>
    loop.run_until_complete(vehicles())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/./porsche1.py", line 67, in vehicles
    vehicles = await client.getVehicles()
  File "/home/pi/.local/lib/python3.9/site-packages/pyporscheconnectapi/client.py", line 448, in getVehicles
    vehicles = await self._connection.get(
  File "/home/pi/.local/lib/python3.9/site-packages/pyporscheconnectapi/connection.py", line 241, in get
    headers = await self._createhead(application)
  File "/home/pi/.local/lib/python3.9/site-packages/pyporscheconnectapi/connection.py", line 295, in _createhead
    token = await self._requestToken(
  File "/home/pi/.local/lib/python3.9/site-packages/pyporscheconnectapi/connection.py", line 210, in _requestToken
    await self._login()
  File "/home/pi/.local/lib/python3.9/site-packages/pyporscheconnectapi/connection.py", line 131, in _login
    self.auth_state["client"] = params["client"][0]
KeyError: 'client'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9b12f9d0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f9b12ed60>, 141281.36447408)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f9b12fa30>

**Comment by RossValler** [comment]
I am seeing the same issues. I suspect Porsche changed something with their API. A quick inspection on the Porsche login site, the endpoints they're calling as part of the login flow are different.

**Comment by maccalove** [comment]
the same issue，waiting

**Comment by fastlorenzo** [comment]
Same here, it looks like this is the flow from the Android app:

![image](https://github.com/CJNE/pyporscheconnectapi/assets/768639/46c8b45e-7362-4b61-9021-c2bb7d673086)

In a nutshell:

1. Click on Login in the app
2. Opens a web page (first query) which redirects to the first step page
3. First step: enter email, click next, redirects to second step
4. Second step: enter password, click next, redirects to a "resume" phase
5. Redirects to the Android app with the auth code

**Comment by fastlorenzo** [comment]
Made a PR that is working on my side with the new authentication flow, if anyone could test it and confirm that'd be great #35

**Comment by RossValler** [comment]
> Made a PR that is working on my side with the new authentication flow, if anyone could test it and confirm that'd be great #35

Confirmed working on 2020 Taycan 4S.

**Comment by augmentedtraffic** [comment]
> Made a PR that is working on my side with the new authentication flow, if anyone could test it and confirm that'd be great #35

confirmed on my side that it now works again - thanks!

**Comment by barto64** [comment]
Happy to test it also, but honestly I do not know how, I only use the ha custom component, not de api directly. If there is a way to test it from the ha (maybe changing something in the manifest). I could do it.
