### ISSUE TITLE
{Q} Time between requests without captcha getting activated

### ISSUE THREAD

**Issue by TimoD87** [CJNE/pyporscheconnectapi#43]
What times between requests did you figure out, without getting "banned" from Porsche side with captcha? (Is there a difference when charging? (Means can you pull request more often, when car is charging?)

Greetings Timo

**Comment by Dual01** [comment]
I experience the same problem, that a captcha alwas appears. So I have to login and logout serevral times via web browser to get it work again.
Additionally, when I start to retrieve the data, I get the following message but data retrieval works:
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x73545850>
transport: <_SelectorSocketTransport fd=6 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:260                                                                                                                               9)

**Comment by fredriklj** [comment]
I am closing this issue as the APIs we relied on have been retired. C.f #46
