### ISSUE TITLE
Failed Setup, will retry 'Nickname'

### ISSUE THREAD

**Issue by CTRDevelopments** [CJNE/pyporscheconnectapi#47]
I have tried to install this, but I am getting the same error as previous.

I have run 

pip install pyporscheconnectapi 

in terminal and it reported success, but I am still stuck. 

It did give me this warning though. Not sure what it means unfortunately

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Any thoughts?

cheers

**Comment by fredriklj** [comment]
Please see #46
